#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Mori Yoshimi <Viimaple1001@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys

def day_water(weight):
    return weight * 0.033

for line in sys.stdin:
    try:
        weight = float(line.strip())
        if weight <= 0:
            sys.exit(1)
        print(f"{day_water(weight):.2f}")
    except:
        sys.exit(1)    

